export const elements = [
  {
    "name": "Hydrogen ",
    "symbol": "H",
    "groupClassification": "Non-Metal",
    "groupName": "Alkali Metals",
    "atomicNumber": 1,
    "atomicMass": 1.00794,
    "charges": "(+1)",
    "electronegativity": 2.2,
    "electronAffinity": "(–73)",
    "ionizationEnergy": 1312,
    "atomicRadius": "53"
  },
  {
    "name": "Helium ",
    "symbol": "He",
    "groupClassification": "Non-Metal",
    "groupName": "Noble Gases",
    "atomicNumber": 2,
    "atomicMass": 4.003,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 2372,
    "atomicRadius": "31"
  },
  {
    "name": "Lithium",
    "symbol": "Li",
    "groupClassification": "Metal",
    "groupName": "Alkali Metals",
    "atomicNumber": 3,
    "atomicMass": 6.941,
    "charges": "(+1)",
    "electronegativity": 1,
    "electronAffinity": "(–60)",
    "ionizationEnergy": 520,
    "atomicRadius": "167"
  },
  {
    "name": "Beryllium",
    "symbol": "Be",
    "groupClassification": "Metal",
    "groupName": "Alkaline Earth Metals",
    "atomicNumber": 4,
    "atomicMass": 9.012182,
    "charges": "(+2)",
    "electronegativity": 1.5,
    "electronAffinity": "0",
    "ionizationEnergy": 899,
    "atomicRadius": "112"
  },
  {
    "name": "Boron",
    "symbol": "B",
    "groupClassification": "Metalloid",
    "groupName": "N/A",
    "atomicNumber": 5,
    "atomicMass": 10.811,
    "charges": "(+3) ",
    "electronegativity": 2,
    "electronAffinity": "(–27)",
    "ionizationEnergy": 801,
    "atomicRadius": "87"
  },
  {
    "name": "Carbon",
    "symbol": "C",
    "groupClassification": "Non-Metal",
    "groupName": "N/A",
    "atomicNumber": 6,
    "atomicMass": 12.0107,
    "charges": "(-4), (+4)",
    "electronegativity": 2.5,
    "electronAffinity": "(–122)",
    "ionizationEnergy": 1086,
    "atomicRadius": "67"
  },
  {
    "name": "Nitrogen",
    "symbol": "N",
    "groupClassification": "Non-Metal",
    "groupName": "Pnictogens",
    "atomicNumber": 7,
    "atomicMass": 14.00674,
    "charges": "(-3)",
    "electronegativity": 3,
    "electronAffinity": "(+7)",
    "ionizationEnergy": 1402,
    "atomicRadius": "56"
  },
  {
    "name": "Oxygen",
    "symbol": "O",
    "groupClassification": "Non-Metal",
    "groupName": "Chalcogens",
    "atomicNumber": 8,
    "atomicMass": 15.9994,
    "charges": "(-2)",
    "electronegativity": 3.5,
    "electronAffinity": "(–141)",
    "ionizationEnergy": 1314,
    "atomicRadius": "48"
  },
  {
    "name": "Fluorine",
    "symbol": "F",
    "groupClassification": "Non-Metal",
    "groupName": "Halogens",
    "atomicNumber": 9,
    "atomicMass": 18.9984032,
    "charges": "(-1)",
    "electronegativity": 4,
    "electronAffinity": "(–328)",
    "ionizationEnergy": 1681,
    "atomicRadius": "42"
  },
  {
    "name": "Neon",
    "symbol": "Ne",
    "groupClassification": "Non-Metal",
    "groupName": "Noble Gases",
    "atomicNumber": 10,
    "atomicMass": 20.1797,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 2081,
    "atomicRadius": "38"
  },
  {
    "name": "Sodium",
    "symbol": "Na",
    "groupClassification": "Metal",
    "groupName": "Alkali Metals",
    "atomicNumber": 11,
    "atomicMass": 22.98977,
    "charges": "(+1)",
    "electronegativity": 0.9,
    "electronAffinity": "(–53)",
    "ionizationEnergy": 496,
    "atomicRadius": "190"
  },
  {
    "name": "Magnesium",
    "symbol": "Mg",
    "groupClassification": "Metal",
    "groupName": "Alkaline Earth Metals",
    "atomicNumber": 12,
    "atomicMass": 24.305,
    "charges": "(+2)",
    "electronegativity": 1.2,
    "electronAffinity": "0",
    "ionizationEnergy": 738,
    "atomicRadius": "145"
  },
  {
    "name": "Aluminum",
    "symbol": "Al",
    "groupClassification": "Metal",
    "groupName": "N/A",
    "atomicNumber": 13,
    "atomicMass": 26.981538,
    "charges": "(+3) ",
    "electronegativity": 1.5,
    "electronAffinity": "(–43)",
    "ionizationEnergy": 578,
    "atomicRadius": "118"
  },
  {
    "name": "Silicon",
    "symbol": "Si",
    "groupClassification": "Metalloid",
    "groupName": "N/A",
    "atomicNumber": 14,
    "atomicMass": 28.0855,
    "charges": "(-4), (+4)",
    "electronegativity": 1.8,
    "electronAffinity": "(–134)",
    "ionizationEnergy": 786,
    "atomicRadius": "111"
  },
  {
    "name": "Phosphorus",
    "symbol": "P",
    "groupClassification": "Non-Metal",
    "groupName": "Pnictogens",
    "atomicNumber": 15,
    "atomicMass": 30.973761,
    "charges": "(-3)",
    "electronegativity": 2.1,
    "electronAffinity": "(–72)",
    "ionizationEnergy": 1012,
    "atomicRadius": "98"
  },
  {
    "name": "Sulfur",
    "symbol": "S",
    "groupClassification": "Non-Metal",
    "groupName": "Chalcogens",
    "atomicNumber": 16,
    "atomicMass": 32.066,
    "charges": "(-2)",
    "electronegativity": 2.5,
    "electronAffinity": "(–200)",
    "ionizationEnergy": 1000,
    "atomicRadius": "88"
  },
  {
    "name": "Chlorine",
    "symbol": "Cl",
    "groupClassification": "Non-Metal",
    "groupName": "Halogens",
    "atomicNumber": 17,
    "atomicMass": 35.4527,
    "charges": "(-1)",
    "electronegativity": 3,
    "electronAffinity": "(–349)",
    "ionizationEnergy": 1251,
    "atomicRadius": "79"
  },
  {
    "name": "Argon",
    "symbol": "Ar",
    "groupClassification": "Non-Metal",
    "groupName": "Noble Gases",
    "atomicNumber": 18,
    "atomicMass": 39.948,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 1521,
    "atomicRadius": "71"
  },
  {
    "name": "Potassium",
    "symbol": "K",
    "groupClassification": "Metal",
    "groupName": "Alkali Metals",
    "atomicNumber": 19,
    "atomicMass": 39.0983,
    "charges": "(+1)",
    "electronegativity": 0.8,
    "electronAffinity": "(–48)",
    "ionizationEnergy": 419,
    "atomicRadius": "243"
  },
  {
    "name": "Calcium",
    "symbol": "Ca",
    "groupClassification": "Metal",
    "groupName": "Alkaline Earth Metals",
    "atomicNumber": 20,
    "atomicMass": 40.078,
    "charges": "(+2)",
    "electronegativity": 1,
    "electronAffinity": "(–2)",
    "ionizationEnergy": 590,
    "atomicRadius": "194"
  },
  {
    "name": "Scandium",
    "symbol": "Sc",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 21,
    "atomicMass": 44.95591,
    "charges": "(+3)",
    "electronegativity": 1.3,
    "electronAffinity": "(–18)",
    "ionizationEnergy": 633,
    "atomicRadius": "184"
  },
  {
    "name": "Titanium",
    "symbol": "Ti",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 22,
    "atomicMass": 47.867,
    "charges": "(+4)",
    "electronegativity": 1.5,
    "electronAffinity": "(–8)",
    "ionizationEnergy": 659,
    "atomicRadius": "176"
  },
  {
    "name": "Vanadium",
    "symbol": "V",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 23,
    "atomicMass": 50.9415,
    "charges": "(+5)",
    "electronegativity": 1.6,
    "electronAffinity": "(–51)",
    "ionizationEnergy": 651,
    "atomicRadius": "171"
  },
  {
    "name": "Chromium",
    "symbol": "Cr",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 24,
    "atomicMass": 51.9961,
    "charges": "(+3), (+6)",
    "electronegativity": 1.6,
    "electronAffinity": "(–64)",
    "ionizationEnergy": 653,
    "atomicRadius": "166"
  },
  {
    "name": "Manganese",
    "symbol": "Mn",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 25,
    "atomicMass": 54.938049,
    "charges": "(+2), (+4), (+7)",
    "electronegativity": 1.5,
    "electronAffinity": "0",
    "ionizationEnergy": 717,
    "atomicRadius": "161"
  },
  {
    "name": "Iron",
    "symbol": "Fe",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 26,
    "atomicMass": 55.845,
    "charges": "(+2), (+3) ",
    "electronegativity": 1.8,
    "electronAffinity": "(–16)",
    "ionizationEnergy": 762,
    "atomicRadius": "156"
  },
  {
    "name": "Cobalt",
    "symbol": "Co",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 27,
    "atomicMass": 58.9332,
    "charges": "(+2), (+3) ",
    "electronegativity": 1.8,
    "electronAffinity": "(–64)",
    "ionizationEnergy": 760,
    "atomicRadius": "152"
  },
  {
    "name": "Nickel",
    "symbol": "Ni",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 28,
    "atomicMass": 58.6934,
    "charges": "(+2)",
    "electronegativity": 1.8,
    "electronAffinity": "(–112)",
    "ionizationEnergy": 737,
    "atomicRadius": "149"
  },
  {
    "name": "Copper",
    "symbol": "Cu",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 29,
    "atomicMass": 63.546,
    "charges": "(+2)",
    "electronegativity": 1.9,
    "electronAffinity": "(–118)",
    "ionizationEnergy": 745,
    "atomicRadius": "145"
  },
  {
    "name": "Zinc",
    "symbol": "Zn",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 30,
    "atomicMass": 65.39,
    "charges": "(+2)",
    "electronegativity": 1.6,
    "electronAffinity": "0",
    "ionizationEnergy": 906,
    "atomicRadius": "142"
  },
  {
    "name": "Gallium",
    "symbol": "Ga",
    "groupClassification": "Metal",
    "groupName": "N/A",
    "atomicNumber": 31,
    "atomicMass": 69.723,
    "charges": "(+3)",
    "electronegativity": 1.6,
    "electronAffinity": "(–30)",
    "ionizationEnergy": 579,
    "atomicRadius": "136"
  },
  {
    "name": "Germanium",
    "symbol": "Ge",
    "groupClassification": "Metalloid",
    "groupName": "N/A",
    "atomicNumber": 32,
    "atomicMass": 72.61,
    "charges": "(-4), (+2), (+4)",
    "electronegativity": 1.8,
    "electronAffinity": "(–119)",
    "ionizationEnergy": 762,
    "atomicRadius": "125"
  },
  {
    "name": "Arsenic",
    "symbol": "As",
    "groupClassification": "Metalloid",
    "groupName": "Pnictogens",
    "atomicNumber": 33,
    "atomicMass": 74.9216,
    "charges": "(-3), (+3), (+5)",
    "electronegativity": 2,
    "electronAffinity": "(–78)",
    "ionizationEnergy": 947,
    "atomicRadius": "114"
  },
  {
    "name": "Selenium",
    "symbol": "Se",
    "groupClassification": "Non-Metal",
    "groupName": "Chalcogens",
    "atomicNumber": 34,
    "atomicMass": 78.96,
    "charges": "(-2)",
    "electronegativity": 2.4,
    "electronAffinity": "(–195)",
    "ionizationEnergy": 941,
    "atomicRadius": "103"
  },
  {
    "name": "Bromine",
    "symbol": "Br",
    "groupClassification": "Non-Metal",
    "groupName": "Halogens",
    "atomicNumber": 35,
    "atomicMass": 79.904,
    "charges": "(-1)",
    "electronegativity": 2.8,
    "electronAffinity": "(–325)",
    "ionizationEnergy": 1140,
    "atomicRadius": "94"
  },
  {
    "name": "Krypton",
    "symbol": "Kr",
    "groupClassification": "Non-Metal",
    "groupName": "Noble Gases",
    "atomicNumber": 36,
    "atomicMass": 83.8,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 1351,
    "atomicRadius": "88"
  },
  {
    "name": "Rubidium",
    "symbol": "Rb",
    "groupClassification": "Metal",
    "groupName": "Alkali Metals",
    "atomicNumber": 37,
    "atomicMass": 85.4678,
    "charges": "(+1)",
    "electronegativity": 0.8,
    "electronAffinity": "(–47)",
    "ionizationEnergy": 403,
    "atomicRadius": "265"
  },
  {
    "name": "Strontium",
    "symbol": "Sr",
    "groupClassification": "Metal",
    "groupName": "Alkaline Earth Metals",
    "atomicNumber": 38,
    "atomicMass": 87.62,
    "charges": "(+2)",
    "electronegativity": 1,
    "electronAffinity": "(–5)",
    "ionizationEnergy": 549,
    "atomicRadius": "219"
  },
  {
    "name": "Yttrium",
    "symbol": "Y",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 39,
    "atomicMass": 88.90585,
    "charges": "(+3)",
    "electronegativity": 1.2,
    "electronAffinity": "(–30)",
    "ionizationEnergy": 600,
    "atomicRadius": "212"
  },
  {
    "name": "Zirconium",
    "symbol": "Zr",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 40,
    "atomicMass": 91.224,
    "charges": "(+4)",
    "electronegativity": 1.4,
    "electronAffinity": "(–41)",
    "ionizationEnergy": 640,
    "atomicRadius": "206"
  },
  {
    "name": "Niobium",
    "symbol": "Nb",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 41,
    "atomicMass": 92.90638,
    "charges": "(+5)",
    "electronegativity": 1.6,
    "electronAffinity": "(–86)",
    "ionizationEnergy": 652,
    "atomicRadius": "198"
  },
  {
    "name": "Molybdenum",
    "symbol": "Mo",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 42,
    "atomicMass": 95.94,
    "charges": "(+4), )+6)",
    "electronegativity": 1.8,
    "electronAffinity": "(–72)",
    "ionizationEnergy": 684,
    "atomicRadius": "190"
  },
  {
    "name": "Technetium",
    "symbol": "Tc",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 43,
    "atomicMass": 98,
    "charges": "(+4), (+7)",
    "electronegativity": 1.9,
    "electronAffinity": "(–53)",
    "ionizationEnergy": 702,
    "atomicRadius": "183"
  },
  {
    "name": "Ruthenium",
    "symbol": "Ru",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 44,
    "atomicMass": 101.07,
    "charges": "(+3), (+4)",
    "electronegativity": 2.2,
    "electronAffinity": "(–101)",
    "ionizationEnergy": 710,
    "atomicRadius": "178"
  },
  {
    "name": "Rhodium",
    "symbol": "Rh",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 45,
    "atomicMass": 102.9055,
    "charges": "(+3)",
    "electronegativity": 2.2,
    "electronAffinity": "(–110)",
    "ionizationEnergy": 720,
    "atomicRadius": "173"
  },
  {
    "name": "Palladium",
    "symbol": "Pd",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 46,
    "atomicMass": 106.42,
    "charges": "(+2), (+4)",
    "electronegativity": 2.2,
    "electronAffinity": "(–54)",
    "ionizationEnergy": 804,
    "atomicRadius": "169"
  },
  {
    "name": "Silver",
    "symbol": "Ag",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 47,
    "atomicMass": 107.8682,
    "charges": "(+1)",
    "electronegativity": 1.9,
    "electronAffinity": "(–126)",
    "ionizationEnergy": 731,
    "atomicRadius": "165"
  },
  {
    "name": "Cadmium",
    "symbol": "Cd",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 48,
    "atomicMass": 112.411,
    "charges": "(+2)",
    "electronegativity": 1.7,
    "electronAffinity": "0",
    "ionizationEnergy": 868,
    "atomicRadius": "161"
  },
  {
    "name": "Indium",
    "symbol": "In",
    "groupClassification": "Metal",
    "groupName": "N/A",
    "atomicNumber": 49,
    "atomicMass": 114.818,
    "charges": "(+3)",
    "electronegativity": 1.7,
    "electronAffinity": "(–29)",
    "ionizationEnergy": 558,
    "atomicRadius": "156"
  },
  {
    "name": "Tin",
    "symbol": "Sn",
    "groupClassification": "Metal",
    "groupName": "N/A",
    "atomicNumber": 50,
    "atomicMass": 118.71,
    "charges": "(+2), (+4)",
    "electronegativity": 1.8,
    "electronAffinity": "(–107)",
    "ionizationEnergy": 709,
    "atomicRadius": "145"
  },
  {
    "name": "Antimony",
    "symbol": "Sb",
    "groupClassification": "Metalloid",
    "groupName": "Pnictogens",
    "atomicNumber": 51,
    "atomicMass": 121.76,
    "charges": "(-3), (+3), (+5)",
    "electronegativity": 1.9,
    "electronAffinity": "(–103)",
    "ionizationEnergy": 834,
    "atomicRadius": "133"
  },
  {
    "name": "Tellurium",
    "symbol": "Te",
    "groupClassification": "Metalloid",
    "groupName": "Chalcogens",
    "atomicNumber": 52,
    "atomicMass": 127.6,
    "charges": "(-2)",
    "electronegativity": 2.1,
    "electronAffinity": "(–190)",
    "ionizationEnergy": 869,
    "atomicRadius": "123"
  },
  {
    "name": "Iodine",
    "symbol": "I",
    "groupClassification": "Non-Metal",
    "groupName": "Halogens",
    "atomicNumber": 53,
    "atomicMass": 126.90447,
    "charges": "(-1)",
    "electronegativity": 2.5,
    "electronAffinity": "(–295)",
    "ionizationEnergy": 1008,
    "atomicRadius": "115"
  },
  {
    "name": "Xenon",
    "symbol": "Xe",
    "groupClassification": "Non-Metal",
    "groupName": "Noble Gases",
    "atomicNumber": 54,
    "atomicMass": 131.29,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 1170,
    "atomicRadius": "108"
  },
  {
    "name": "Cesium",
    "symbol": "Cs",
    "groupClassification": "Metal",
    "groupName": "Alkali Metals",
    "atomicNumber": 55,
    "atomicMass": 132.90545,
    "charges": "(+1)",
    "electronegativity": 0.7,
    "electronAffinity": "(–46)",
    "ionizationEnergy": 376,
    "atomicRadius": "298"
  },
  {
    "name": "Barium",
    "symbol": "Ba",
    "groupClassification": "Metal",
    "groupName": "Alkaline Earth Metals",
    "atomicNumber": 56,
    "atomicMass": 137.327,
    "charges": "(+2)",
    "electronegativity": 0.9,
    "electronAffinity": "(–14)",
    "ionizationEnergy": 503,
    "atomicRadius": "253"
  },
  {
    "name": "Lanthanum",
    "symbol": "La",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 57,
    "atomicMass": 138.9055,
    "charges": "(+3)",
    "electronegativity": 1.1,
    "electronAffinity": "(–48)",
    "ionizationEnergy": 538,
    "atomicRadius": "N/A"
  },
  {
    "name": "Cerium",
    "symbol": "Ce",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 58,
    "atomicMass": 140.116,
    "charges": "(+3), (+4)",
    "electronegativity": 1.1,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 534,
    "atomicRadius": "N/A"
  },
  {
    "name": "Praseodymium",
    "symbol": "Pr",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 59,
    "atomicMass": 140.90765,
    "charges": "(+3)",
    "electronegativity": 1.1,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 527,
    "atomicRadius": "247"
  },
  {
    "name": "Neodymium",
    "symbol": "Nd",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 60,
    "atomicMass": 144.24,
    "charges": "(+3)",
    "electronegativity": 1.1,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 533,
    "atomicRadius": "206"
  },
  {
    "name": "Promethium",
    "symbol": "Pm",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 61,
    "atomicMass": 145,
    "charges": "(+3)",
    "electronegativity": 1.2,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 540,
    "atomicRadius": "205"
  },
  {
    "name": "Samarium",
    "symbol": "Sm",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 62,
    "atomicMass": 150.36,
    "charges": "(+3)",
    "electronegativity": 1.2,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 544,
    "atomicRadius": "238"
  },
  {
    "name": "Europium",
    "symbol": "Eu",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 63,
    "atomicMass": 151.964,
    "charges": "(+2), (+3)",
    "electronegativity": 1.1,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 547,
    "atomicRadius": "231"
  },
  {
    "name": "Gadolinium",
    "symbol": "Gd",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 64,
    "atomicMass": 157.25,
    "charges": "(+3)",
    "electronegativity": 1.2,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 593,
    "atomicRadius": "233"
  },
  {
    "name": "Terbium",
    "symbol": "Tb",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 65,
    "atomicMass": 158.92534,
    "charges": "(+3)",
    "electronegativity": 1.2,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 566,
    "atomicRadius": "225"
  },
  {
    "name": "Dysprosium",
    "symbol": "Dy",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 66,
    "atomicMass": 162.5,
    "charges": "(+3)",
    "electronegativity": 1.2,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 573,
    "atomicRadius": "228"
  },
  {
    "name": "Holmium",
    "symbol": "Ho",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 67,
    "atomicMass": 164.93032,
    "charges": "(+3)",
    "electronegativity": 1.2,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 581,
    "atomicRadius": "226"
  },
  {
    "name": "Erbium",
    "symbol": "Er",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 68,
    "atomicMass": 167.26,
    "charges": "(+3)",
    "electronegativity": 1.2,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 589,
    "atomicRadius": "226"
  },
  {
    "name": "Thulium",
    "symbol": "Tm",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 69,
    "atomicMass": 168.93421,
    "charges": "(+3)",
    "electronegativity": 1.2,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 597,
    "atomicRadius": "222"
  },
  {
    "name": "Ytterbium",
    "symbol": "Yb",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 70,
    "atomicMass": 173.04,
    "charges": "(+3)",
    "electronegativity": 1.2,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 603,
    "atomicRadius": "222"
  },
  {
    "name": "Lutetium",
    "symbol": "Lu",
    "groupClassification": "Metal",
    "groupName": "Lanthanides",
    "atomicNumber": 71,
    "atomicMass": 174.967,
    "charges": "(+3)",
    "electronegativity": 1.3,
    "electronAffinity": "(–50)",
    "ionizationEnergy": 523,
    "atomicRadius": "217"
  },
  {
    "name": "Hafnium",
    "symbol": "Hf",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 72,
    "atomicMass": 178.49,
    "charges": "(+4)",
    "electronegativity": 1.3,
    "electronAffinity": "0",
    "ionizationEnergy": 658,
    "atomicRadius": "208"
  },
  {
    "name": "Tantalum",
    "symbol": "Ta",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 73,
    "atomicMass": 180.9479,
    "charges": "(+5)",
    "electronegativity": 1.5,
    "electronAffinity": "(–31)",
    "ionizationEnergy": 761,
    "atomicRadius": "200"
  },
  {
    "name": "Tungsten",
    "symbol": "W",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 74,
    "atomicMass": 183.84,
    "charges": "(+4), (+6)",
    "electronegativity": 1.7,
    "electronAffinity": "(–79)",
    "ionizationEnergy": 770,
    "atomicRadius": "193"
  },
  {
    "name": "Rhenium",
    "symbol": "Re",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 75,
    "atomicMass": 186.207,
    "charges": "(+4)",
    "electronegativity": 1.9,
    "electronAffinity": "(–15)",
    "ionizationEnergy": 760,
    "atomicRadius": "188"
  },
  {
    "name": "Osmium",
    "symbol": "Os",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 76,
    "atomicMass": 190.23,
    "charges": "(+4)",
    "electronegativity": 2.2,
    "electronAffinity": "(–106)",
    "ionizationEnergy": 840,
    "atomicRadius": "185"
  },
  {
    "name": "Iridium ",
    "symbol": "Ir",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 77,
    "atomicMass": 192.217,
    "charges": "(+3), (+4)",
    "electronegativity": 2.2,
    "electronAffinity": "(–151)",
    "ionizationEnergy": 880,
    "atomicRadius": "180"
  },
  {
    "name": "Platinum",
    "symbol": "Pt",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 78,
    "atomicMass": 195.078,
    "charges": "(+2), (+4)",
    "electronegativity": 2.2,
    "electronAffinity": "(–205)",
    "ionizationEnergy": 870,
    "atomicRadius": "177"
  },
  {
    "name": "Gold",
    "symbol": "Au",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 79,
    "atomicMass": 196.96655,
    "charges": "(+3)",
    "electronegativity": 2.4,
    "electronAffinity": "(–222)",
    "ionizationEnergy": 890,
    "atomicRadius": "174"
  },
  {
    "name": "Mercury ",
    "symbol": "Hg",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 80,
    "atomicMass": 200.59,
    "charges": "(+1), (+2)",
    "electronegativity": 1.9,
    "electronAffinity": "0",
    "ionizationEnergy": 1007,
    "atomicRadius": "171"
  },
  {
    "name": "Thallium",
    "symbol": "Tl",
    "groupClassification": "Metal",
    "groupName": "N/A",
    "atomicNumber": 81,
    "atomicMass": 204.3833,
    "charges": "(+1), (+3)",
    "electronegativity": 1.8,
    "electronAffinity": "(–19)",
    "ionizationEnergy": 589,
    "atomicRadius": "156"
  },
  {
    "name": "Lead",
    "symbol": "Pb",
    "groupClassification": "Metal",
    "groupName": "N/A",
    "atomicNumber": 82,
    "atomicMass": 207.2,
    "charges": "(+2), (+4)",
    "electronegativity": 1.9,
    "electronAffinity": "(–35)",
    "ionizationEnergy": 716,
    "atomicRadius": "154"
  },
  {
    "name": "Bismuth",
    "symbol": "Bi",
    "groupClassification": "Metal",
    "groupName": "Pnictogens",
    "atomicNumber": 83,
    "atomicMass": 208.98038,
    "charges": "(+3)",
    "electronegativity": 1.9,
    "electronAffinity": "(–91)",
    "ionizationEnergy": 703,
    "atomicRadius": "143"
  },
  {
    "name": "Polonium",
    "symbol": "Po",
    "groupClassification": "Metal",
    "groupName": "Chalcogens",
    "atomicNumber": 84,
    "atomicMass": 209,
    "charges": "(-2), (+2), (+4)",
    "electronegativity": 2,
    "electronAffinity": "(–183)",
    "ionizationEnergy": 812,
    "atomicRadius": "135"
  },
  {
    "name": "Astatine",
    "symbol": "At",
    "groupClassification": "Metalloid",
    "groupName": "Halogens",
    "atomicNumber": 85,
    "atomicMass": 210,
    "charges": "(-1)",
    "electronegativity": 2.2,
    "electronAffinity": "(–270)",
    "ionizationEnergy": 890,
    "atomicRadius": "127"
  },
  {
    "name": "Radon",
    "symbol": "Rn",
    "groupClassification": "Non-Metal",
    "groupName": "Noble Gases",
    "atomicNumber": 86,
    "atomicMass": 222,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 1037,
    "atomicRadius": "120"
  },
  {
    "name": "Francium",
    "symbol": "Fr",
    "groupClassification": "Metal",
    "groupName": "Alkali Metals",
    "atomicNumber": 87,
    "atomicMass": 223,
    "charges": "(+1)",
    "electronegativity": 0.7,
    "electronAffinity": "0",
    "ionizationEnergy": 380,
    "atomicRadius": "N/A"
  },
  {
    "name": "Radium",
    "symbol": "Ra",
    "groupClassification": "Metal",
    "groupName": "Alkaline Earth Metals",
    "atomicNumber": 88,
    "atomicMass": 226,
    "charges": "(+2)",
    "electronegativity": 0.9,
    "electronAffinity": "0",
    "ionizationEnergy": 509,
    "atomicRadius": "N/A"
  },
  {
    "name": "Actinium",
    "symbol": "Ac",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 89,
    "atomicMass": 227,
    "charges": "(+3)",
    "electronegativity": 1.1,
    "electronAffinity": "0",
    "ionizationEnergy": 499,
    "atomicRadius": "N/A"
  },
  {
    "name": "Thorium",
    "symbol": "Th",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 90,
    "atomicMass": 232.0381,
    "charges": "(+4)",
    "electronegativity": 1.5,
    "electronAffinity": "0",
    "ionizationEnergy": 587,
    "atomicRadius": "N/A"
  },
  {
    "name": "Protactinium",
    "symbol": "Pa",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 91,
    "atomicMass": 231.03588,
    "charges": "(+5)",
    "electronegativity": 1.5,
    "electronAffinity": "0",
    "ionizationEnergy": 568,
    "atomicRadius": "N/A"
  },
  {
    "name": "Uranium",
    "symbol": "U",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 92,
    "atomicMass": 238.0289,
    "charges": "(+6)",
    "electronegativity": 1.7,
    "electronAffinity": "0",
    "ionizationEnergy": 598,
    "atomicRadius": "N/A"
  },
  {
    "name": "Neptunium",
    "symbol": "Np",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 93,
    "atomicMass": 237,
    "charges": "(+5)",
    "electronegativity": 1.3,
    "electronAffinity": "0",
    "ionizationEnergy": 604,
    "atomicRadius": "N/A"
  },
  {
    "name": "Plutonium",
    "symbol": "Pu",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 94,
    "atomicMass": 244,
    "charges": "(+4)",
    "electronegativity": 1.3,
    "electronAffinity": "0",
    "ionizationEnergy": 585,
    "atomicRadius": "N/A"
  },
  {
    "name": "Americium",
    "symbol": "Am",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 95,
    "atomicMass": 243,
    "charges": "(+3)",
    "electronegativity": 1.3,
    "electronAffinity": "0",
    "ionizationEnergy": 578,
    "atomicRadius": "N/A"
  },
  {
    "name": "Curium",
    "symbol": "Cm",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 96,
    "atomicMass": 247,
    "charges": "(+3)",
    "electronegativity": 1.3,
    "electronAffinity": "0",
    "ionizationEnergy": 581,
    "atomicRadius": "N/A"
  },
  {
    "name": "Berkelium",
    "symbol": "Bk",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 97,
    "atomicMass": 247,
    "charges": "(+3)",
    "electronegativity": 1.3,
    "electronAffinity": "0",
    "ionizationEnergy": 601,
    "atomicRadius": "N/A"
  },
  {
    "name": "Californium",
    "symbol": "Cf",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 98,
    "atomicMass": 251,
    "charges": "(+3)",
    "electronegativity": 1.3,
    "electronAffinity": "0",
    "ionizationEnergy": 608,
    "atomicRadius": "N/A"
  },
  {
    "name": "Einsteinium",
    "symbol": "Es",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 99,
    "atomicMass": 252,
    "charges": "(+3)",
    "electronegativity": 1.3,
    "electronAffinity": "0",
    "ionizationEnergy": 619,
    "atomicRadius": "N/A"
  },
  {
    "name": "Fermium",
    "symbol": "Fm",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 100,
    "atomicMass": 257,
    "charges": "(+3)",
    "electronegativity": 1.3,
    "electronAffinity": "0",
    "ionizationEnergy": 627,
    "atomicRadius": "N/A"
  },
  {
    "name": "Mendelevium",
    "symbol": "Md",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 101,
    "atomicMass": 258,
    "charges": "(+3)",
    "electronegativity": 1.3,
    "electronAffinity": "0",
    "ionizationEnergy": 635,
    "atomicRadius": "N/A"
  },
  {
    "name": "Nobelium",
    "symbol": "No",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 102,
    "atomicMass": 259,
    "charges": "(+2)",
    "electronegativity": 1.5,
    "electronAffinity": "0",
    "ionizationEnergy": 642,
    "atomicRadius": "N/A"
  },
  {
    "name": "Lawrencium",
    "symbol": "Lr",
    "groupClassification": "Metal",
    "groupName": "Actinides",
    "atomicNumber": 103,
    "atomicMass": 262,
    "charges": "(+3)",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 470,
    "atomicRadius": "N/A"
  },
  {
    "name": "Rutherfordium",
    "symbol": "Rf",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 104,
    "atomicMass": 261,
    "charges": "(+4)",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 580,
    "atomicRadius": "N/A"
  },
  {
    "name": "Dubnium",
    "symbol": "Db",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 105,
    "atomicMass": 262,
    "charges": "(+5)",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Seaborgium",
    "symbol": "Sg",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 106,
    "atomicMass": 263,
    "charges": "(+6)",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Bohrium",
    "symbol": "Bh",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 107,
    "atomicMass": 262,
    "charges": "(+7)",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Hassium",
    "symbol": "Hs",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 108,
    "atomicMass": 265,
    "charges": "(+8)",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Meitnerium",
    "symbol": "Mt",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 109,
    "atomicMass": 266,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Darmstadtium",
    "symbol": "Ds",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 110,
    "atomicMass": 269,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Roentgenium",
    "symbol": "Rg",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 111,
    "atomicMass": 272,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Copemicium",
    "symbol": "Cn",
    "groupClassification": "Metal",
    "groupName": "Transition Metals",
    "atomicNumber": 112,
    "atomicMass": 277,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Nihonium",
    "symbol": "Nh",
    "groupClassification": "Metal",
    "groupName": "N/A",
    "atomicNumber": 113,
    "atomicMass": 286,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Flerovium",
    "symbol": "Fl",
    "groupClassification": "Metal",
    "groupName": "N/A",
    "atomicNumber": 114,
    "atomicMass": 289,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Moscovium",
    "symbol": "Mc",
    "groupClassification": "Metal",
    "groupName": "Pnictogens",
    "atomicNumber": 115,
    "atomicMass": 290,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Livermorium",
    "symbol": "Lv",
    "groupClassification": "Metal",
    "groupName": "Chalcogens",
    "atomicNumber": 116,
    "atomicMass": 293,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Tennessine",
    "symbol": "Ts",
    "groupClassification": "Metal",
    "groupName": "Halogens",
    "atomicNumber": 117,
    "atomicMass": 294,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  },
  {
    "name": "Oganesson",
    "symbol": "Og",
    "groupClassification": "Non-Metal",
    "groupName": "Noble Gases",
    "atomicNumber": 118,
    "atomicMass": 294,
    "charges": "0",
    "electronegativity": 0,
    "electronAffinity": "0",
    "ionizationEnergy": 0,
    "atomicRadius": "N/A"
  }
]
